# Set permissions for the job to allow it to write to the repository
    permissions:
      contents: write

    steps:
      # 1. Checks out a copy of your repository
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. THIS IS THE REQUIRED STEP
      - name: Step with email 23f2000659@ds.study.iitm.ac.in
        run: echo "This step has the required email in its name."

      # 3. This step creates the commit
      - name: Create or update a file and commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          echo "Last run: $(date)" > last_run.txt
          git add last_run.txt
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automated daily commit"
            git push
          else
            echo "No changes to commit."
          fi
